apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - svc.yaml
images:
  - name: himanshumaurya1920/node-app-2
    newTag: 1.0.0
  - name: docker.io/himanshumaurya1920/node-app-2
    newName: docker.io/himanshumaurya1920/node-app-2
    newTag: 1.0.1
